displayName: taxifare_20220715_230427
studySpec:
  metrics:
  - metricId: val_rmse
    goal: MINIMIZE
  parameters:
  - parameterId: lr
    doubleValueSpec:
      minValue: 0.0001
      maxValue: 0.1
    scaleType: UNIT_LOG_SCALE
  - parameterId: nbuckets
    integerValueSpec:
      minValue: 10
      maxValue: 25
    scaleType: UNIT_LINEAR_SCALE
  - parameterId: batch_size
    discreteValueSpec:
     values:
     - 15
     - 30
     - 50
    scaleType: UNIT_LINEAR_SCALE
  - parameterId: embed_output_dim
    integerValueSpec:
      minValue: 5
      maxValue: 12
    scaleType: UNIT_LINEAR_SCALE
  algorithm: ALGORITHM_UNSPECIFIED
trialJobSpec:
  baseOutputDirectory:
    outputUriPrefix: gs://qwiklabs-asl-01-1d0b6cba208c/taxifare_20220715_230427
  workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-4
    pythonPackageSpec:
      args:
      - --train_data_path=gs://qwiklabs-asl-01-1d0b6cba208c/taxifare/data/taxi-train*
      - --eval_data_path=gs://qwiklabs-asl-01-1d0b6cba208c/taxifare/data/taxi-valid*
      - --batch_size=15
      - --num_examples_to_train_on=100
      - --num_evals=10
      - --nbuckets=10
      - --lr=0.001
      - --embed_output_dim=5
      - --nnsize=32 8
      executorImageUri: us-docker.pkg.dev/vertex-ai/training/tf-cpu.2-8:latest
      packageUris:
      - gs://qwiklabs-asl-01-1d0b6cba208c/taxifare/taxifare_trainer_embed_tune-0.1.tar.gz
      pythonModule: trainer.task
    replicaCount: 1
